@extends('layouts.main')

@section('content')
    <table>
        <tr>
            <th>NIK</th>
            <th>Nama</th>
            <th>Tempat/tanggal lahir</th>
            <th>Jenis_kelamin</th>
            <th>Alamat</th>
            <th>RT</th>
            <th>RW</th>
            <th>Desa</th>
            <th>Kecamatan</th>
            <th>Agama</th>
            <th>Status</th>
            <th>Pekerjaan</th>
            <th>Kewarganegaraan</th>
            <th>Opsi</th>
        </tr>
        <tr>
            @foreach ($data as $d)
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            @endforeach
        </tr>
    </table>
@endsection
